### ISSUE TITLE
[CHORE] 기초세팅

### ISSUE THREAD

**Issue by Larry7939** [SOPT-31-3/Triple-Android#1]
## 💡 Issue
기초세팅
## 📝 todo
- [x]  StyleGuide적용
- [x]  Typograpy
- [x]  package분리
- [x]  implementation 적용
- [x]  manifest 에 서버 추가하기
- [x]  git igonre추가

**Comment by cbj0010** [comment]
아 맞아 슨생님 manifest에 http 쓸 수 있게 해주는 것도 넣어주심 감사하겟슴니다!
